### ISSUE TITLE
cannot use IRIS15 with SDK 3.9 in Ubuntu 20.04

### ISSUE THREAD

**Issue by kasliwalr** [Photometrics/PyVCAM#10]
I am having trouble using the IRIS15 camera, it is not being detected. I think I followed all the instructions for installation of `pvcam` and `pvcam-sdk` in downloaded [3.9.4.2 zip file](https://www.photometrics.com/support/software-and-drivers).  Here is what I tried

```
> sudo usermod -a -G users user_name
# reboot computer
# all previous pvcam/pvcam-sdk installation were removed
> sudo dpkg -i pvcam_3.9.4.2-1_amd64.deb pvcam-sdk_3.9.4.2-1_amd64.deb 
> sudo poweroff
# power cycle camera, wait 45 sec
# boot PC
# run examples/pvcamtest
```
Operating system: 5.8.0-38-generic #43~20.04.1-Ubuntu SMP
Also attached snapshot of installation instructions used and errors generated when running `PVCamTest` and `ImageSequence` sdk example binary. 

![pvcam_issues](https://user-images.githubusercontent.com/11048931/105258128-e8b15300-5b3d-11eb-8fb5-e4e93bbcb752.png)

**Comment by stevebellinger** [comment]
We are looking into this issue.

**Comment by stevebellinger** [comment]
We are working to replicate your problem. Are you using USB or PCIe?

**Comment by kasliwalr** [comment]
> We are working to replicate your problem. Are you using USB or PCIe?

PCIe

**Comment by stevebellinger** [comment]
There was a mix-up with the Linux PVCAM and PVCAM SDK posted on the website. Please re-download the installers and re-install. Sorry for the confusion.

**Comment by kasliwalr** [comment]
Its working. Thanks
