### ISSUE TITLE
clarification on api

### ISSUE THREAD

**Issue by kasliwalr** [Photometrics/PyVCAM#12]
**System information:** 
- Ubuntu 20.04
- PCIe IRIS15
- Python 3.9.1
- PVCAM SDK 3.9...
- PyVCAM: https://github.com/Photometrics/PyVCAM/commit/110fcf474f601ee4f8b87ab9c2f90f19d80c539a

Could you clarify how `PyVCAM` API corresponds to `PVCAM SDK` C++ API for the following cases:

1.  I would like to do software-triggered live/sequence acquisition, at maximum possible speed. I was trying to adapt the `sw_trigger.py` example but it seems the `start_live` or `start_sequence` API do not wait for software-trigger. If you comment out the `TriggerThreadRun` section as shown below, you would expect the `start_live()` to wait forever, but instead it runs to completion. 

```
# example: [sw_trigger.py](https://github.com/Photometrics/PyVCAM/blob/master/pyvcam_wrapper/tests/sw_trigger.py)
def main():
    # Initialize PVCAM and find the first available camera.
    pvc.init_pvcam()

    cam = [cam for cam in Camera.detect_camera()][0]
    cam.open()
    cam.speed_table_index = 0
    cam.exp_mode = 'Edge Trigger'
    print(cam.exp_modes)
    # Start a thread for executing the trigger
    # t1 = TriggerThreadRun(cam)
    # t1.start()

    # Collect frames in live mode
    cam.start_live()
    framesReceived = collectFrames(cam)
    cam.finish()
    print('Received live frames: ' + str(framesReceived) + '\n')

    # Collect frames in sequence mode
    # cam.start_seq(num_frames=NUM_FRAMES)
    # framesReceived = collectFrames(cam)
    # cam.finish()
    # print('Received seq frames: ' + str(framesReceived) + '\n')

    # t1.stop()
    cam.close()
    pvc.uninit_pvcam()

    print('Done')
```

2. ~How you set buffer size in `PyVCAM` API: I would like to do sequence acquisition, but I want to set the buffer size to say 100 frames worth of space, how can I do that using `PyVCAM` API? If I cannot do that, how to find the buffer size, what is the default?~ Looking at the .cpp code does clarify things for me (correct me if I am wrong) - allocating memory based on number of frames passed

3. ~`poll_frame`: In `start_seq`, what happens if `poll_frame` is called at a slower rate than FPS? will the underlying buffer be overwritten? In C++ SDK, one could set the buffer size and is thus assured that it will not be overwritten. In live acquisition (C++), the buffer is overwritten if circular mode is set.~ When using `poll_frame`, are frames returned in `FIFO` order? Also, have you confirmed that `poll_frame` times-out when trigger is not received. I tried with `Edge trigger` and the program kept waiting for trigger. Can we set timeout from Python API?

**Comment by stevebellinger** [comment]
1. IRIS15 doesn't support software trigger.
2. Correct, memory is allocated based on the number of frames requested.
3. Frames are returned in FIFO order. You can not set a poll_frame time out. I have added this feature to our backlog for a future release, but that will likely not be ready until the end of March. Do you need this feature in the near term? If so, it can be implemented in a branch.

**Comment by kasliwalr** [comment]
Thanks! for the clarification. poll_frame timeout is not a big/urgent issue for us, a "monitoring" thread in python to interrupt the acquisition should do the trick I think.

**Comment by stevebellinger** [comment]
Yes, that should work.

**Comment by kasliwalr** [comment]
I also don't see any option to set buffer size of circular buffer in `start_live`. It is set to 16 frames ~ 500MB. Can you make this settable?

**Comment by stevebellinger** [comment]
I have added a feature to our backlog to add support for specifying the buffer size in live mode. Let me know if you need this in a branch prior to the release.

**Comment by kasliwalr** [comment]
prior to release, and as soon as possible if you can. will hard-coding in `c++` file, and reinstalling `PyVCAM` work?

**Comment by stevebellinger** [comment]
Yes, hard-coding the number of frames will work. Please see pvcmodule.cpp:517

**Comment by kasliwalr** [comment]
does `PyVCAM`'s `poll_frame()` return a copy of the frame, or is it still referencing the memory in the circular buffer. I need to know if I have to do copying in python to protect the frame?

**Comment by stevebellinger** [comment]
Yes, a copy occurs. Please see camera.py:374
