### ISSUE TITLE
DLL load failed while importing pvc: The operating system cannot run %1

### ISSUE THREAD

**Issue by zerobotics** [Photometrics/PyVCAM#13]
Hi, when I try to import pvc as '_from pyvcam import pvc_' I get the following error; 
**DLL load failed while importing pvc: The operating system cannot run %1**

The setup.py is installed successfully; 
************************************************************

Operating system: Windows
Machine architecture: AMD64
************************************************************

Pre-install necessary packages as admin

   python -m pip install --upgrade pip setuptools wheel numpy  

************************************************************

Build package:     python setup.py build

Install package:   python setup.py install

Create Wheel dist: python setup.py sdist bdist_wheel

Uninstall package: pip uninstall pyvcam

************************************************************

C:\Program Files\Photometrics\PVCamSDK\
running install
running bdist_egg
running egg_info
writing pyvcam.egg-info\PKG-INFO
writing dependency_links to pyvcam.egg-info\dependency_links.txt
writing top-level names to pyvcam.egg-info\top_level.txt
reading manifest file 'pyvcam.egg-info\SOURCES.txt'
writing manifest file 'pyvcam.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
creating build\bdist.win-amd64\egg
creating build\bdist.win-amd64\egg\pyvcam
copying build\lib.win-amd64-3.9\pyvcam\camera.py -> build\bdist.win-amd64\egg\pyvcam
copying build\lib.win-amd64-3.9\pyvcam\constants.py -> build\bdist.win-amd64\egg\pyvcam
copying build\lib.win-amd64-3.9\pyvcam\pvc.cp39-win_amd64.pyd -> build\bdist.win-amd64\egg\pyvcam
copying build\lib.win-amd64-3.9\pyvcam\__init__.py -> build\bdist.win-amd64\egg\pyvcam
byte-compiling build\bdist.win-amd64\egg\pyvcam\camera.py to camera.cpython-39.pyc
byte-compiling build\bdist.win-amd64\egg\pyvcam\constants.py to constants.cpython-39.pyc
byte-compiling build\bdist.win-amd64\egg\pyvcam\__init__.py to __init__.cpython-39.pyc
creating stub loader for pyvcam\pvc.cp39-win_amd64.pyd
byte-compiling build\bdist.win-amd64\egg\pyvcam\pvc.py to pvc.cpython-39.pyc
creating build\bdist.win-amd64\egg\EGG-INFO
copying pyvcam.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
copying pyvcam.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying pyvcam.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying pyvcam.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
writing build\bdist.win-amd64\egg\EGG-INFO\native_libs.txt
zip_safe flag not set; analyzing archive contents...
pyvcam.__pycache__.pvc.cpython-39: module references __file__
creating 'dist\pyvcam-2.1.0-py3.9-win-amd64.egg' and adding 'build\bdist.win-amd64\egg' to it
removing 'build\bdist.win-amd64\egg' (and everything under it)
Processing pyvcam-2.1.0-py3.9-win-amd64.egg
removing 'c:\users\magnetic pc\appdata\local\programs\python\python39\lib\site-packages\pyvcam-2.1.0-py3.9-win-amd64.egg' (and everything under it)
creating c:\users\magnetic pc\appdata\local\programs\python\python39\lib\site-packages\pyvcam-2.1.0-py3.9-win-amd64.egg
Extracting pyvcam-2.1.0-py3.9-win-amd64.egg to c:\users\magnetic pc\appdata\local\programs\python\python39\lib\site-packages
pyvcam 2.1.0 is already the active version in easy-install.pth

Installed c:\users\magnetic pc\appdata\local\programs\python\python39\lib\site-packages\pyvcam-2.1.0-py3.9-win-amd64.egg
Processing dependencies for pyvcam==2.1.0
Finished processing dependencies for pyvcam==2.1.0

*************** Finished ***************

Can you help me with this issue?

Thanks!

**Comment by stevebellinger** [comment]
Can you please tell me which version of PVCAM and PVCAM SDK you have installed?

**Comment by zerobotics** [comment]
Hi, 

Application version: 1.2.16
PVCAM version: 3.8.0.6-PMQI
PVCAM 32bit Core library (SYSTEM) version: 8.1.1314.0
PVCAM 32bit DDI library (SYSTEM) version: 2.0.128.0
PVCAM 64bit Core library (SYSTEM) version: 8.1.1314.0
PVCAM 64bit DDI library (SYSTEM) version: 2.0.128.0
PVCAM Core library (LOCAL) version: N / A
PVCAM DDI library (LOCAL) version: N / A
Device Driver version: UNKNOWN

SDK for PVCAM 3.9.0

PyVcam is the latest one available in GitHub

**Comment by zerobotics** [comment]
Hi, I have updated PVCAM with the latest (3.9.3.4) and it is working now. Thank you for your help.
