### ISSUE TITLE
ImportError: DLL load failed: The operating system cannot run %1.

### ISSUE THREAD

**Issue by rkshthrmsh** [Photometrics/PyVCAM#17]
I am working in an Anaconda environment and have successfully installed PVCAM, PVCAM SDK, and PyVCAM. When I try to run the live_mode.py test, I am seeing the following error:

```
C:\Users\<user_name>\PyVCAM\pyvcam_wrapper\tests>python live_mode.py
Traceback (most recent call last):
  File "live_mode.py", line 5, in <module>
    from pyvcam import pvc
ImportError: DLL load failed: The operating system cannot run %1.

```
The following are installed in the environment site-packages:

```
 Directory of C:\Users\<user_name>\anaconda3\envs\calcium_imaging\Lib\site-packages
2021-06-17  05:00 PM    <DIR>          pyvcam
2021-06-17  05:00 PM    <DIR>          pyvcam-2.1.0.dist-info
               0 File(s)              0 bytes
               2 Dir(s)  882,605,125,632 bytes free

```
Please let me know if anymore information is required.

**Comment by stevebellinger** [comment]
Please provide the PVCAM and PVCAM SDK version you have installed. If the latest version from the website is not installed, please upgrade.

https://www.photometrics.com/support/software-and-drivers

**Comment by rkshthrmsh** [comment]
Hi stevebellinger, 
Installed software versions are:
PVCAM: 3.9.5.6
PVCAM SDK: 3.9.3.4

**Comment by stevebellinger** [comment]
In the past this error has indicated that PyVCAM was built against a different version of the PVCAM .dll then what actually resides in System32. Perhaps pyvcam was built prior to installing the latest versions PVCAM and PVCAM SDK?

**Comment by rkshthrmsh** [comment]
Uninstalling, and reinstalling the relevant software and packages in the following order worked:

1. PVCAM 3.9.5.6
2. PVCAM SDK 3.9.3.4
3. PyVCAM

Thanks!
