### ISSUE TITLE
exp_time Parameter Left Out of get_sequence 

### ISSUE THREAD

**Issue by hsmSCUFFY** [Photometrics/PyVCAM#19]
Hello,

I'm kind of new to this stuff so I'm sorry if I'm not using the right words or if I'm posting this in the wrong spot. I was playing around with this wonderful code and I was having some issues with the get_sequence() method in the Camera class in camera.py. I was able to take pictures using things like get_frame() and poll_frame() but for some reason all of my pictures with get_sequence() were very dark even after setting exp_time to be 1000! So then I took a look at get_sequence() in camera.py and it looks like there's an exp_time parameter but when get_frame() is called inside of get_sequence() the exp_time parameter is not passed onto get_frame().

I believe it's a pretty simple fix but I thought I should bring it up.

inside of get_sequence()  in camera.py I turned :
stack[i] = self.get_frame()

into:
stack[i] = self.get_frame(exp_time = exp_time)

I apologize for not knowing where to post this, if I've used the wrong words or maybe if  this "error" is not an error at all. Please let me know, thank you!

**Comment by stevebellinger** [comment]
Thank you for finding this bug. I will apply the fix shortly.
