### ISSUE TITLE
Issue while compiling

### ISSUE THREAD

**Issue by mcgurk94** [Photometrics/PyVCAM#2]
I've been consistently getting an error while trying to install with the setup file.

I'm currently running with Python 3.6 (32 bit) and compiling with visual studio 2019 - I've tried uninstalling and using an older version of VS (2015) but it spat out the same errors while compiling.

This might be entirely user error, but is there any guidance you could offer to help get this installed?

Creating library build\temp.win32-3.7\Release\src/pyvcam\pvc.cp37-win32.lib and object build\temp.win32-3.7\Release\src/pyvcam\pvc.cp37-win32.exp
pvcmodule.obj : error LNK2001: unresolved external symbol _pl_cam_open@12
pvcmodule.obj : error LNK2001: unresolved external symbol _pl_exp_get_latest_frame@8
pvcmodule.obj : error LNK2001: unresolved external symbol _pl_exp_check_status@12
pvcmodule.obj : error LNK2001: unresolved external symbol _pl_get_param@16
pvcmodule.obj : error LNK2001: unresolved external symbol _pl_get_enum_param@24
pvcmodule.obj : error LNK2001: unresolved external symbol _pl_cam_get_total@4
pvcmodule.obj : error LNK2001: unresolved external symbol _pl_exp_abort@8
pvcmodule.obj : error LNK2001: unresolved external symbol _pl_exp_stop_cont@8
pvcmodule.obj : error LNK2001: unresolved external symbol _pl_cam_close@4
pvcmodule.obj : error LNK2001: unresolved external symbol _pl_pvcam_uninit@0
pvcmodule.obj : error LNK2001: unresolved external symbol _pl_enum_str_length@16
pvcmodule.obj : error LNK2001: unresolved external symbol _pl_cam_get_name@8
pvcmodule.obj : error LNK2001: unresolved external symbol _pl_exp_setup_seq@28
pvcmodule.obj : error LNK2001: unresolved external symbol _pl_error_code@0
pvcmodule.obj : error LNK2001: unresolved external symbol _pl_pvcam_init@0
pvcmodule.obj : error LNK2001: unresolved external symbol _pl_cam_register_callback_ex3@16
pvcmodule.obj : error LNK2001: unresolved external symbol _pl_exp_start_seq@8
pvcmodule.obj : error LNK2001: unresolved external symbol _pl_pp_reset@4
pvcmodule.obj : error LNK2001: unresolved external symbol _pl_exp_setup_cont@28
pvcmodule.obj : error LNK2001: unresolved external symbol _pl_exp_start_cont@12
pvcmodule.obj : error LNK2001: unresolved external symbol _pl_error_message@8
pvcmodule.obj : error LNK2001: unresolved external symbol _pl_set_param@12
pvcmodule.obj : error LNK2001: unresolved external symbol _pl_exp_check_cont_status@16
pvcmodule.obj : error LNK2001: unresolved external symbol _pl_pvcam_get_ver@4
build\lib.win32-3.7\pyvcam\pvc.cp37-win32.pyd : fatal error LNK1120: 24 unresolved externals
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.20.27508\\bin\\HostX86\\x86\\link.exe' failed with exit status 1120

**Comment by HerrZiffer** [comment]
The symbols look decorated.  Be certain you have the 32-bit PVCAM installed - 64 bit functions are not decorated by the compiler. No reason 32-bit should be a problem provided everything matches.  In general we suggest using 64-bit PVCAM.  Is there a requirement pushing you to use 32-bit?

**Comment by mcgurk94** [comment]
Thanks, I'll see if I can make any progress with this when I'm back in the office.

There's no reason I can't move on to use the 64 bit version of pvcam if that's what you recommend; the lab replaced their prehistoric laptops fairly recently but kept most of the software the same, I can update them if required.

**Comment by mcgurk94** [comment]
Just retried the install with your advice and it all went smoothly this time, thanks for your help
