### ISSUE TITLE
Read speed is lower than expected

### ISSUE THREAD

**Issue by fabinjoe** [Photometrics/PyVCAM#21]
I am using a Retiga Electro Camera to obtain a live data stream. I have been using the PyVCAM to obtain the data from the camera. The camera is connected through an USB3.0 port. The camera claims to obtain the output at 25fps. 
However, I wrote the following snippet of code to obtain the time taken to read a frame from get_frame() function. 
 
```
cam.open()
cam.start_live(exp_time=20)

for i in range(100):
	t0 = time()
	frame = cam.get_frame()
	print( time() - t0 )
```
From running the code, I have observed that it takes more than 120ms to read a frame(as plotted below). This gives us an average output frame-rate of 8.33 (which is much lower than the expected value).  
Additionally using cam.readout_time gives an output which is an order of magnitude less than what we obtained(about 12ms).

![screenshot](https://user-images.githubusercontent.com/66658906/125832439-8a9f2b33-d416-423b-b646-4a34791bae97.jpg)
 
I was wondering if this is expected from using the PyVCAM module, and whether there are methods to optimize the read speed performance.

**Comment by stevebellinger** [comment]
Can you please repeat the frame rate test using poll_frame rather than get_frame?

See tests/live_mode.py for an example.

**Comment by fabinjoe** [comment]
Thank you so much for the reply, this method did improve the speed. Now we are receiving an output similar to that of the camera specifications.
