### ISSUE TITLE
binning X

### ISSUE THREAD

**Issue by julienGautier77** [Photometrics/PyVCAM#24]
Hi
Thanks for developping this python wrapper.
I have a problem with Binning only in X
I think the problem is in self.read_enum(const.PARAM_BINNING_SER).values() in the bin_X.setter function.

I think it should be remplaced by  (like in binY.setter fucntion ) :  
self.read_enum(const.PARAM_BINNING_PAR).values()

Are you agree ?

Thanks in advance

**Comment by lwalder** [comment]
Hi Julien, what exactly is the problem on your side, do you get an error or what are the symptoms?
The `PARAM_BINNING_SER` and `PARAM_BINNIG_PAR` parameters report list of allowed binning factors in x and y direction, respectively. We cannot use the `PARAM_BINNIG_PAR` in the x-direction binning setter.
For example, if:
`PARAM_BINNING_SER` reports `1, 2, 3, 4` and
`PARAM_BINNING_PAR` reports `1, 4, 6, 8`
then the binning modes the application is allowed to set is `1x1`, `2x4`, `3x6` or `4x8`. If the application tries to set, for example, `2x2`, then an error will be reported.

**Comment by lwalder** [comment]
There was, however, a minor issue in the exception message handling in the `bin_y` setter. Fixed in [639def9].

**Comment by julienGautier77** [comment]
The minor issue change the problem
I didn't see it 
Thanks
