### ISSUE TITLE
Hello and request for a PyPI release

### ISSUE THREAD

**Issue by AhmetCanSolak** [Photometrics/PyVCAM#25]
Hello,

Thank you for a great SDK and a python wrapper! We started using it recently here @czbiohub and loving it.
I was wondering if there is any chance for you to make a PyPI release so we can depend on PyVCAM in our projects.
This would make the life much easier for the users of the packages we develop.
Happy to contribute and help as well, please let me know.

**Comment by lwalder** [comment]
Hello, thank you for your suggestion! We have not considered releasing the PyVCAM through PyPI yet but since there seems to be growing interest we will look into that and consider it for future releases.
