### ISSUE TITLE
configuring multiple output triggers for kinetix

### ISSUE THREAD

**Issue by kochalka** [Photometrics/PyVCAM#26]
I would like to configure my Kinetix to use multiple output triggers as described in pp26-27 of the [manual](https://www.photometrics.com/wp-content/uploads/2021/11/Kinetix-Manual-58-723-004_RevA01.pdf). Is this possible with pyvcam? If so, how do I do it? Thanks!

**Comment by lwalder** [comment]
Hello, you should be able to use the `camera.set_param` function together with `PARAM_TRIGTAB_SIGNAL` and `PARAM_LAST_MUXED_SIGNAL`. Please refer to the PVCAM documentation:
https://www.photometrics.com/docs/pvcam-sdk/_triggering_table.xhtml
