### ISSUE TITLE
Enquiry on white balance

### ISSUE THREAD

**Issue by pfizer-nuskhanlab-ipp** [Photometrics/PyVCAM#29]
Dear Sir/Mdm,

I’ve manually extracted the R, G and B reference values for white , using the PVCAMTEST software>>Color tab.

I am trying to do a white balance using the extracted R, G and B reference in pyvcam and am wondering how I can do so. Would appreciate if you could advise if this is possible?
Thank you!

Regards,
Ariel

**Comment by tomhanak** [comment]
PVCAM SDK contains ```PVCamTest``` source code. Take a look at ```TaskSet_ConvertToRgb8.cpp``` file. It is quite complex but maybe you will be able to extract just a small part for your use case...
