### ISSUE TITLE
Updating constants.py

### ISSUE THREAD

**Issue by ffvoigt** [Photometrics/PyVCAM#3]
Thanks for creating this wrapper for PVCAM, it is a lot of fun to use.

I have a small request: Recently released versions of PVCAM (I'm running 3.8) included new camera options, including the Programmable Scan Mode which exposes new entries in `constants.py` such as:
```python
PARAM_SCAN_MODE = ((CLASS3<<16) + (TYPE_ENUM<<24)      + 250)
PARAM_SCAN_DIRECTION = ((CLASS3<<16) + (TYPE_ENUM<<24)      + 251)
PARAM_SCAN_DIRECTION_RESET = ((CLASS3<<16) + (TYPE_BOOLEAN<<24)      + 252)
PARAM_SCAN_LINE_DELAY = ((CLASS3<<16) + (TYPE_UNS16<<24)      + 253)
PARAM_SCAN_LINE_TIME = ((CLASS3<<16) + (TYPE_INT64<<24)      + 254)
```
While it is possible to manually run `constants_generator.py` and to exchange `constants.py` to get access to these new parameters, it would be great if you could update pyvcam so that these parameters are accessible by default after installation.

Thanks!

**Comment by HerrZiffer** [comment]
We have this working internally - just need some intern power to merge and update the Git.  If you send a note to your local sales or service wand request engineering support, they will pass it on to us, and I can email you the files directly.  We will update the git - but have a lot on the boil at the moment - will be a few weeks at least.

**Comment by ffvoigt** [comment]
Sorry for asking again, but have you been able to push this further internally? It would be great if the offical repository could be updated at some point to make the installation easier for our users. And, yes, I also requested this through my offical sales contact.

**Comment by HerrZiffer** [comment]
New constants_generator.py and constants.py supporting PSM and Centroiding in branch.  New PSM example in tests. Will merge after additional validation.

**Comment by HerrZiffer** [comment]
Validated, ready for merge
