### ISSUE TITLE
How to set rolling or global shutter

### ISSUE THREAD

**Issue by Rabo98** [Photometrics/PyVCAM#36]
Good morning to everybody.

I want to change the shutter of my camera from "rolling" to "global". Unfortunately, I could not find it in the PyVCAM folder here on GitHub.
Can someone help me please?
Thank you very much.

**Comment by tomhanak** [comment]
Rolling or global shutter can be set via ```exp_out_mode``` property on ```Camera``` class. All available modes are reported via ```exp_out_modes``` property.
