### ISSUE TITLE
Recording coloured images

### ISSUE THREAD

**Issue by Fabian-dfm** [Photometrics/PyVCAM#37]
Dear Sir or Madam,

I would like to know how i can obtain RGB images instead of black/white images with the pyvcam package. The image arrays only have 1 value per pixel and I know that the camera is capable of recording rgb values for each pixel.

Best regards

**Comment by tomhanak** [comment]
No Photometrics camera provides RGB values for each pixel. The color camera still uses monochromatic sensor with color filter array (CFA) on the sensor. So each pixel has assigned only one color based on Bayer mask. Please read more about it e.g. on [wiki](https://en.wikipedia.org/wiki/Bayer_filter).

To get an RGB image, the raw pixels from the camera must go through debayering/demosaicing first. It is quite complex topic, read more e.g. on [wiki](https://en.wikipedia.org/wiki/Demosaicing).

In Python, an [OpenCV](https://docs.opencv.org/3.4/de/d25/imgproc_color_conversions.html) can be used with ```cv2.COLOR_Bayer*``` values, like [here](https://www.geeksforgeeks.org/convert-bgr-and-rgb-with-python-opencv/).
