### ISSUE TITLE
ImportError: DLL load failed

### ISSUE THREAD

**Issue by SebastianVivoverse** [Photometrics/PyVCAM#39]
### Error

Get the following error when trying to run:

```python
from pyvcam import pvcam
```

```shell
ImportError: DLL load failed while importing pvc: The specified module could not be found.
```

### Steps to reproduce

OS: Windows 11
Python: 3.11.5
PVCAM_SDK60: 3.10.1.1

1. git clone PyVCAM repo
2. Activate your venv
3. Run python setup.py install
4. Attempt to import pvc from pyvcam in python

### Added Context

This was working just fine until I tried to build a wheel from the pyvcam wrapper package. After that the error persists.

**Comment by vondrejPM** [comment]
The PyVCAM wrapper needs both PVCAM and PVCAM_SDK in order to work properly. Kindly make sure that you have both installed. You can download latest PVCAM from this link: https://www.photometrics.com/support/download/pvcam

**Comment by SebastianVivoverse** [comment]
My bad, it's working now thanks!
