### ISSUE TITLE
installation steps for ubuntu

### ISSUE THREAD

**Issue by kasliwalr** [Photometrics/PyVCAM#6]
Hi, 

I am trying to use PyVCAM on my test setup. As per your instruction, I did python3 installation. Now, when I am trying to install PyVCAM, I am getting the following error

```
# System details
# Linux/Kernel version:  4.15.0-112-generic #113~16.04.1-Ubuntu
# PVCAM version: 3.8.1.6PVCAM 
# SDK version: 3.8.1
# IRIS connection type, PCIe or USB3: PCIe
> python3 --version
   Python 3.9.1
> cd dir_containing_setup.py
> python3 setup.py install

Traceback (most recent call last):
  File "/home/rishabh/repos/3rd_party/PyVCAM/pyvcam_wrapper/setup.py", line 2, in <module>
    from setuptools import setup, find_packages
  File "/usr/local/lib/python3.9/site-packages/setuptools/__init__.py", line 23, in <module>
    from setuptools.dist import Distribution
  File "/usr/local/lib/python3.9/site-packages/setuptools/dist.py", line 34, in <module>
    from setuptools import windows_support
  File "/usr/local/lib/python3.9/site-packages/setuptools/windows_support.py", line 2, in <module>
    import ctypes
  File "/usr/local/lib/python3.9/ctypes/__init__.py", line 8, in <module>
    from _ctypes import Union, Structure, Array
ModuleNotFoundError: No module named '_ctypes'
```

As some forums online suggested, I tried installing `libffi-dev` and repeated the install. got the same error.

**Comment by stevebellinger** [comment]
Hello Rishabh,

I have just completed a major update to PyVCAM. Please checkout the latest version of the repository and try again. If your problems persist I will be happy to support you.

Thank you,
Steve

**Comment by kasliwalr** [comment]
Hi Steve, 

I just learned from one of the issues, that the latest version of PyVCAM will not work on Linux. I prefer Linux, could you send me the unreleased version of the SDK for trial? If not, will the previous version of PyVCAM work with old sdk (PVCAM 3.8.1)

Thanks!
